python train_classifier.py \
    --model_name "google-bert/bert-large-uncased" \
    --dataset_name "sameearif/CSB-Classifier" \
    --output_dir "./experiments/csb_run_v1" \
    --learning_rate 1e-5 \
    --batch_size 8 \
    --gradient_accumulation_steps 2 \
    --epochs 10 \
    --weight_decay 0.01 \
    --max_length 512 \
    --seed 42 \
    --push_to_hub \
    --hub_model_id "sameearif/bert-large-csb"